CREATE TABLE COURIERCOMPANY(
    courierID VARCHAR2(10),
    courierName VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_courierID PRIMARY KEY(courierID)
);

INSERT INTO
    COURIERCOMPANY
VALUES
    ('CR1001', 'POSLAJU');

INSERT INTO
    COURIERCOMPANY
VALUES
    ('CR1002', 'DHL');

INSERT INTO
    COURIERCOMPANY
VALUES
    ('CR1003', 'SKYNET');

INSERT INTO
    COURIERCOMPANY
VALUES
    ('CR1004', 'NINJAVAN');

INSERT INTO
    COURIERCOMPANY
VALUES
    ('CR1005', 'J&T');