CREATE TABLE Cart (
    Cart_ID SMALLINT IDENTITY(000001, 1) PRIMARY KEY NOT NULL,
    Cus_ID SMALLINT FOREIGN KEY REFERENCES Customer(Cus_ID),
    Order_ID SMALLINT FOREIGN KEY REFERENCES Orders(Order_ID),
    Total_Items SMALLINT,
    Total_Price REAL,
);